# Generated by Django 4.2.2 on 2023-06-29 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_registration_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='last_name',
        ),
    ]
